swagger: "2.0"
info:
  description: "Island API helps you find islands on a map"
  version: "1.0.0"
  title: "Islands API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
tags:
- name: island
  description: "Everything about Islands"
- name: map
  description: "update the maps"
schemes:
- "http"
paths:
  /maps:
    post:
      tags:
      - "map"
      summary: "Refresh maps"
      description: ""
      responses:
        '200':
          description: OK
  /islands:
    get:
      tags:
      - island
      summary: "Retrieve all islands with their respective tiles"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Island"
        404:
          description: "No islands found in DB. Please check if Maps operation was executed since startup. "

  /islands/{id}:
    get:
      tags:
      - island
      summary: "ID of island"
      description: "Returns a single island by id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of island to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Island"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Island not found"
definitions:
  Island:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      tiles:
        type: "array"
        items:
          $ref: "#/definitions/Tile"
  Tile:
    type: "object"
    properties:
      x:
        type: "integer"
        format: "int32"
      y:
        type: "integer"
        format: "int32"